services:
  # Base de données dédiée pour le Data Warehouse (Chicago Data)
  postgres_data:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chicago_data
    ports:
      - "5433:5432" # EXTERNE (Windows): 5433 | INTERNE (Docker): 5432
